### ISSUE TITLE
Benefits and Motivation

### ISSUE THREAD

**Issue by webdeb** [Steams/ra-data-hasura-graphql#1]
Hi @Steams may I ask you why we should use `ra-data-hasura-graphql`, instead of `ra-data-graphql` and `ra-data-hasura`, could you please explain the benefits of  compared to them?

**Comment by Steams** [comment]
> Hi @Steams may I ask you why we should use `ra-data-hasura-graphql`, instead of `ra-data-graphql` and `ra-data-hasura`, could you please explain the benefits of compared to them?

Hey @webdeb,

This utility is built on top of `ra-data-graphql` and is just a custom data provider for the current Hasura graphql API format. The existing ra-data-hasura data provider uses Hasura V1 which communicates over standard REST API and not GraphQL. This utility auto generates valid graphql queries based on the properties exposed by the Hasura API such as "object_bool_exp" and "object_set_input".

**Comment by webdeb** [comment]
@Steams thanks! I've already tried it out, its looking good so far, has definitive the potential!
I would suggest, that you put the motivation and benefits into the README ;)

**Comment by Steams** [comment]
@webdeb Yeah i'll be sure to add those in, thanks for the suggestion. I'm surprised you found the lib so quickly as it wasn't really intended for release yet, there are still a few aspects I have to clean up but i appreciate your contributions.

**Comment by webdeb** [comment]
I've followed a suggestion here https://github.com/hasura/ra-data-hasura/issues/11#issuecomment-569752267 and tried it! 

So I am also happy to contribute and I'll start to use it myself ;)
