### ISSUE TITLE
pagination problem

### ISSUE THREAD

**Issue by hetaochen** [Steams/ra-data-hasura-graphql#11]
I found that when I turned the page，the total number decreased.
I think it's because not exclude the 'offset' argument in **_buildMetaArgs_**.
`
export const buildMetaArgs = (query, variables,aorFetchType) => {
    if (query.args.length === 0) {
        return [];
    }

    const validVariables = Object.keys(variables).filter(
        k => {
            if(
                aorFetchType === GET_LIST ||
                aorFetchType === GET_MANY ||
                aorFetchType === GET_MANY_REFERENCE
            ) {
                return (typeof variables[k] !== 'undefined' && k !== 'limit');
            }

            return typeof variables[k] !== 'undefined';
        }
    );

    let args = query.args
        .filter(a => validVariables.includes(a.name))
        .reduce(
            (acc, arg) => [
                ...acc,
                gqlTypes.argument(
                    gqlTypes.name(arg.name),
                    gqlTypes.variable(gqlTypes.name(arg.name))
                ),
            ],
            []
        );

    return args;
}`

**Comment by Steams** [comment]
Thanks for noticing and submitting a PR, i've merged it.
