### ISSUE TITLE
BuildQuery.js assumes that tables have an `id` field

### ISSUE THREAD

**Issue by pankgeorg** [Steams/ra-data-hasura-graphql#18]
I set up a simple app and inspected the results of the first query after the introspection:
```{
   "operationName":"company",
   "variables":{
      "where":{
         "_and":[]
},
      "limit":10,
      "offset":0,
      "order_by":{
         "id":"asc"
      }
},
   "query":`query company($limit: Int, $offset: Int, $order_by: [company_order_by!]!, $where: company_bool_exp) {
  items: company(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    company_id
    name
    __typename
  }
  total: company_aggregate(order_by: $order_by, where: $where) {
    aggregate {
      count
      __typename
    }
    __typename
  }
}`
}
```
the query fails with the message: `[GraphQL error]: Message: field "id" not found in type: 'company_order_by', Location: undefined, Path: undefined`.
Indeed, the type does _not_ include an id:
_below the result of running `npx get-graphql-schema --json` against my hasura API_

```
"""
ordering options when selecting data from "company"
"""
input company_order_by {
  companyParentsByParentCompanyId_aggregate: company_parent_aggregate_order_by
  company_details_aggregate: company_detail_aggregate_order_by
  company_id: order_by
  company_parents_aggregate: company_parent_aggregate_order_by
  company_sizes_aggregate: company_size_aggregate_order_by
  name: order_by
}

``` 

As you can see in the order by clause, it says `"id": "asc"` while in the query it's clear there is no id. 

The root cause of this is, as it seems that, `buildGetListVariables` doesn't actually use the introspection results. Also, while [here](https://github.com/Steams/ra-data-hasura-graphql/blob/master/src/buildVariables.js#L53) we use the `params.sort` variable (which looks like it doesn't work), that is not the case [L129](https://github.com/Steams/ra-data-hasura-graphql/blob/master/src/buildVariables.js#L129), [L134](https://github.com/Steams/ra-data-hasura-graphql/blob/master/src/buildVariables.js#L134), [L140](https://github.com/Steams/ra-data-hasura-graphql/blob/master/src/buildVariables.js#L140) and [L160](https://github.com/Steams/ra-data-hasura-graphql/blob/master/src/buildVariables.js#L160), where the `id` is being used bare.
Is having `id` columns a requirement of the current implementation? How can we override that?

**Comment by webdeb** [comment]
Thats a valid point, what do you suggest to do? check if we have the key `id` in the schema, and otherwise skip sorting completely?

**Comment by pankgeorg** [comment]
The issue is more complicated that it seems, I think. The assumption both this db and `ra-data-hasura` do, is that the table has an Id. I guess they need that because hasura doesn't play along with the GraphQL Scalar type `ID`. I'd say further input is needed from the Hasura team (and for sure, I need to understand it better). 

In any case it's introspection's job to find and use an `unique_id`, and it doesn't.
If the introspection doesn't (can't) yield a result, we should expand the greedy strategy to pick it, from selecting `id` (which should be the first pick) to `${table_name}_id` which is a great alternative (because of Postgres' `USING` clause).

**Comment by Steams** [comment]
@pankgeorg The sorting by ID is not a property of this data provider lib, but a property of react-admin itself. It is the react-admin framework that requires that the data is sorted by id and it demands that all "resources" returned from the Hasura endpoint (any endpoint from any provider) have an ID property. [See docs segment on the specifications for a data provider here](https://marmelab.com/react-admin/DataProviders.html#writing-your-own-data-provider)

Similarly for delete, update etc, the only identifying information my lib will receive from react-admin is this ID property.

You do make an interesting suggestion that the introspection should make an attempt to find a property with a unique_id type and use that field, though it would still need to alias that field as id before sending it back to react-admin. I'll look into that.

**Comment by Steams** [comment]
> the query fails with the message: `[GraphQL error]: Message: field "id" not found in type: 'company_order_by', Location: undefined, Path: undefined`.
> Indeed, the type does _not_ include an id:
> As you can see in the order by clause, it says "id": "asc" while in the query it's clear there is no id.

You can bypass this specific issue by explicitly setting a starting sort order on your table which will overwrite the default sorting by id. Though at current, without an id field on your resources, you would quickly run into other errors down the line
