### ISSUE TITLE
Uncaught (in promise) Error: Unknown dataProvider function: getList 

### ISSUE THREAD

**Issue by s-kris** [Steams/ra-data-hasura-graphql#19]
I'm getting the said error when using `react-admin in custom app` without using `<Admin> `as mentioned here: https://marmelab.com/react-admin/CustomApp.html#not-using-the-admin-components .
Any pointers why this is happening?

note: There are no errors when passing dataprovider to `<Admin>` as shown in examples. It's just that I'm trying to use react-admin without `<Admin>` in an existing app.

**Comment by webdeb** [comment]
"Unknown dataProvider function", means there is no `dataProvider`.

Have you wrapped your Components with:

```
<DataProviderContext.Provider value={dataProvider}>
  <YourAppResources />
</DataProviderContext.Provider>
```

?

**Comment by s-kris** [comment]
Yes

**Comment by webdeb** [comment]
Where is the error coming from: `Uncaught (in promise) Error: Unknown dataProvider function: getList` ?

**Comment by s-kris** [comment]
`The above error occurred in the <LocationProvider> component:
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:126)
    in MDXProvider (at wrap-root-element.js:65)
    in MDXScopeProvider (at wrap-root-element.js:64)
    in Unknown
    in Unknown (at wrap-root-element.js:72)
    in _default (at app.js:67)`

Adding a screenshot for clarity.

![Screenshot 2020-03-04 at 3 05 25 PM](https://user-images.githubusercontent.com/3975305/75865461-9aae3680-5e29-11ea-8f2d-e14bd77b2295.png)

Note: the same error is thrown when using https://github.com/hasura/ra-data-hasura as well, if it helps.

**Comment by webdeb** [comment]
`LocationProvider`, is it your custom component?
Could you share a minimal reproducible example?

**Comment by s-kris** [comment]
Sorry, `LocationProvider` is not my custom component. 
Sure, I'll setup a minimal repo and update you.

**Comment by webdeb** [comment]
It may be worth to check out the original `Admin.tsx` implemention. Seems like there exists an `AdminContext` which is responsible to setup the Providers without the `AdminUI` 

https://github.com/marmelab/react-admin/blob/master/packages/react-admin/src/Admin.tsx

**Comment by s-kris** [comment]
Yeah, I followed the documentation here: https://marmelab.com/react-admin/CustomApp.html#not-using-the-admin-components

**Comment by webdeb** [comment]
Are you sure its updated?

**Comment by s-kris** [comment]
I was under the assumption that the react-admin is clear of the coast.
But I'll setup a minimal repo without using `<Admin>`and 
1. test with different dataproviders
2. test ra-data-hasura-graphql

**Comment by s-kris** [comment]
Here is the repo: https://github.com/s-kris/gatsby-react-admin-min-code

Observations in embedding react-admin in custom page
1.  works with ra-data-fakerest (http://localhost:8000/ra-fakerest/#/posts)
2. doesn't work with ra-data-hasura-graphql (http://localhost:8000/ra-hasura/#/posts). Throws the error: `Unknown dataProvider function: getList` (same as before)

**Comment by s-kris** [comment]
Hi @webdeb did you get time to test this?

**Comment by webdeb** [comment]
@s-kris not yet, sorry. But I'll try to find time this week

**Comment by s-kris** [comment]
No problem, stay safe!
Thanks :)

**Comment by lapidus** [comment]
I am having a similar issue with missing getList ...

Logging dataProvider gives me this `(t,n,r)=>e(t,n,r)`.

So I try passing dataProvider as dataProvider(). Then it actually seems to kick in as I get this error message:

`Error: Unknown resource undefined. Make sure it has been declared on your server side schema. Known resources are topic, blog_post, ....`

**Comment by lapidus** [comment]
Sorry, it was solved over here:
https://github.com/Steams/ra-data-hasura-graphql/issues/6
