### ISSUE TITLE
Experiences with Auth providers? Trying to create a secure login

### ISSUE THREAD

**Issue by dvasdekis** [Steams/ra-data-hasura-graphql#20]
Hi all,

Given that React-Admin modules were available for it, I've been trying to integrate [Firebase authentication](https://github.com/benwinding/react-admin-firebase) into the [react-admin-low-code](https://github.com/cpursley/react-admin-low-code) example as a template to start working from.

I've figured out that by importing react-admin-firebase and calling AuthProvider.getPermissions(), I can see my Hasura JWT as generated by Firebase ([following this guide to set up Firebase](https://hasura.io/blog/authentication-and-authorization-using-hasura-and-firebase/)) in console.log. What I can't figure out is how to pass the X-Hasura-User-ID token through as a HTTP header alongside the GraphQL requests that this module makes. [Apollo has a guide to Auth via headers](https://www.apollographql.com/docs/react/networking/authentication/), and it looks like using the 'apollo-link-context' module is how you would set this, but I can't find any method in this module by which to attach it.

How would I pass it through? Failing that, has anyone gotten any SaaS login providers to play nicely with this module?

**Comment by dvasdekis** [comment]
So it seems that I can set a header from the buildHasuraProvider({clientOptions...}) structure, but I'm not seeing the header being sent with the query in my Hasura logs. As per the below (sorry for the verbosity):

```
import React from 'react';
import { Admin, Resource } from 'react-admin';
import { TodoList, TodoEdit, TodoCreate } from './todos';
import { UserList, UserShow } from './users';
import PostIcon from '@material-ui/icons/Book';
import UserIcon from '@material-ui/icons/Group';

// Hasura imports
import buildHasuraProvider from 'ra-data-hasura-graphql';

// Firebase imports
import { FirebaseAuthProvider } from "react-admin-firebase";
import { firebaseConfig as config } from './components/FIREBASE_CONFIG_TEST';

// Define Firebase variables
const firebaseAuthProviderOptions = {
  logging: true,
  rootRef: 'root_collection/some_document',
  watch: ["posts"]
};
const firebaseAuthProvider = FirebaseAuthProvider(config, firebaseAuthProviderOptions);

// App definition
const App = async () => {
    let firebaseAuthPermissions = firebaseAuthProvider.getPermissions();
    let hasuraDataProvider = await buildHasuraProvider({ clientOptions: { uri: process.env.REACT_APP_HASURA_API,
        header: firebaseAuthPermissions }});
    console.log(firebaseAuthPermissions);
    return () => (
        <Admin
            authProvider={firebaseAuthProvider}
            dataProvider={hasuraDataProvider}
        >
            <Resource
                name="todos"
                icon={PostIcon}
                list={TodoList}
                edit={TodoEdit}
                create={TodoCreate}
            />
            <Resource
                name="users"
                icon={UserIcon}
                list={UserList}
                show={UserShow}
            />
        </Admin>
    );
};
export default App;
```
The result of *firebaseAuthPermissions* does seem to be a valid JWT. When it's printed to console, it looks like:
```
[[PromiseValue]]: Object
https://hasura.io/jwt/claims:
x-hasura-default-role: "user"
x-hasura-allowed-roles: ["user"]
x-hasura-user-id: "psSYD5dJfubiwlJIwGphWqxeJT72"
__proto__: Object
iss: "https://securetoken.google.com/my-project"
aud: "my-project"
auth_time: 1583372965
user_id: "psSYD5dJfubiwlJIwGphWqxeJT72"
sub: "psSYD5dJfubiwlJIwGphWqxeJT72"
iat: 1583383737
exp: 1583387337
email: "test2@example.com"
email_verified: false
firebase: {identities: {…}, sign_in_provider: "password"}
```
Hasura is additionally set up for JWT mode. However, I can't see this JWT in my Hasura logs, and additionally the page starts to render the data from Hasura before the JWT is written to console logs.

Any thoughts, folks? I feel like I'm so close, and yet am missing something small.

**Comment by defrex** [comment]
You're close. This should work.

```js
let firebaseJWT = await firebaseAuthProvider.getJWTToken();
let hasuraDataProvider = await buildHasuraProvider({
  clientOptions: { 
    uri: process.env.REACT_APP_HASURA_API,
    headers: {
      authorization: `Bearer ${firebaseJWT}` 
    }
  }
});
```

**Comment by osterwood** [comment]
I am having the same issue, `headers` passed in to `clientOptions` do not appear in the outgoing request.

**Comment by dvasdekis** [comment]
> I was having the same issue, `headers` passed in to `clientOptions` do not appear in the outgoing request.
> 
> Found that changing to creating the Apollo Client myself worked:
> 
> ```
> import ApolloClient from 'apollo-boost';
> const client = new ApolloClient({uri: uri, headers: headers});
> ...
> const dataProvider = await buildHasuraProvider({ client: client });
> ```

Thanks Chris! This worked a treat!! 

I see the authentication in my Hasura logs now - it used to say `"user_vars":{"x-hasura-role":"anonymous"}` and now says 
`"user_vars":{"x-hasura-role":"user","x-hasura-user-id":"---FIREBASEUSERID---"}`. Hasura is succesfully validating the JWT in the background.

I had to `npm i apollo-boost graphql` on top of this package.

For those wondering how I got JWT authentication working with Hasura, here is the [fork of the firebase auth module](https://github.com/benwinding/react-admin-firebase/pull/82), and the [npm module based on the fork](https://www.npmjs.com/package/react-admin-firebase-jwt). Hopefully the author accepts the pull soon, so you can then just use [react-admin-firebase](https://www.npmjs.com/package/react-admin-firebase).

**Comment by Steams** [comment]
```js
const httpLink = createHttpLink({
  uri: graphql_url,
})

const authLink = setContext((_, { headers }) => {
  let token = getJWTFromSomewhere();
  if (token) {
    return {
      headers: {
        ...headers,
        authorization: `Bearer ${token}`,
      },
    }
  }

  return {
    headers: { ...headers },
  }
})

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache(),
})

const hasuraDataProvider = await buildHasuraProvider({
  client: client,
})
```

**Comment by bamarni** [comment]
I'm getting started with React Admin and also trying to use this provider with Firebase Auth. I use this code:

``` javascript
// App.js
const authProvider = FirebaseAuthProvider(firebaseConfig, firebaseOptions);

const httpLink = createHttpLink({
  uri: process.env.REACT_APP_GRAPHQL_URI,
});

const authLink = setContext((_, { headers }) => {
    return authProvider.getJWTToken().then(token => {
        if (token) {
            return {
                headers: {
                    ...headers,
                    Authorization: `Bearer ${token}`
                }
            }
        }
        return headers
    });
});

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, location, path }) =>
      console.log(`[GraphQL error]: Message: ${message}, Location: ${location}, Path: ${path}`),
    );

  if (networkError)
    console.log(`[Network error]: ${networkError}`);
});

const client = new ApolloClient({
  link: errorLink.concat(authLink.concat(httpLink)),
  cache: new InMemoryCache(),
});

const App = () => {
    const [dataProvider, setDataProvider] = React.useState();

    React.useEffect(() => {
        buildHasuraProvider({
          client: client,
        })
        .then((dp) => setDataProvider(() => dp))
    }, []);

    if (!dataProvider) {
        return <div>Loading</div>;
    }

    return (
        <Admin authProvider={authProvider} dataProvider={dataProvider}>
            <Resource name="User" icon={UserIcon} list={UserList} create={UserCreate} edit={UserEdit} />
        </Admin>
    );
};

export default App;
```

This works fine when Hasura is publicly accessible, I can login and on subsequent GraphQL requests the Authorization header will be set with the token. However when I set an admin token, restart Hasura, and logout. I get an error page:

![screenshot-localhost_3000-2020 10 27-11_45_12](https://user-images.githubusercontent.com/1205386/97291226-efd00a00-1849-11eb-923e-9c0d2bca9ecf.png)

What would be the recommended way to redirect to the login page here instead of failing?

**Comment by cpursley** [comment]
@bamarni  ~ take a look at these examples:

https://github.com/cpursley/react-admin-low-code#alternatives

**Comment by bamarni** [comment]
@cpursley : thanks for the link. I've tried with `ra-hasura-typescript-boilerplate` from @hgiasac and I get a similar problem. It works all fine when Hasura is not configured with an admin token, but it doesn't work whenever I set it it like I would do in production. It's frozen on the loading screen:

<img width="1677" alt="Screenshot 2020-10-28 at 15 05 58" src="https://user-images.githubusercontent.com/1205386/97447722-1f594200-1930-11eb-9f2d-73ffe198c156.png">

The error seems related to the introspection query the library needs to do when creating the data provider. It is doing it with the `Authorization: null` header, and Hasura returns that error (`Malformed Authorization header`).

For reference, I'm using the following dev config for Hasura:

``` yaml
HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@localhost:5432/my-db
HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
HASURA_GRAPHQL_DEV_MODE: "true"
HASURA_GRAPHQL_ADMIN_SECRET: GkFRSxoXMNyScrVF5VM5TSc7G6K7fLcfKkUSv44CTMzihpckh4tTB5MTEzMDffLc
HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "my-project", "issuer": "https://securetoken.google.com/my-project"}'
```

(As mentioned before, everything works fine when I remove `HASURA_GRAPHQL_ADMIN_SECRET` and `HASURA_GRAPHQL_JWT_SECRET)

**Comment by dvasdekis** [comment]
@bamarni Are you determined to use the Apollo library? [My solution without it does work](https://github.com/dvasdekis/react-admin-hasura-firebase) (and is working in production) with admin secrets.

For the record, I gave up on the Apollo approach for 2 reasons:
1. Apollo seemed to increase the client JS payload size significantly, without having a tangible 'benefit' to UX
2. It was really complicated to get client token refreshes to work, and I gave up. [See here](https://able.bio/AnasT/apollo-graphql-async-access-token-refresh--470t1c8) for the ongoing ordeal of people trying to work out an approach.

**Comment by bamarni** [comment]
@dvasdekis : Indeed I don't get the error anymore when switching to your solution 👍 

The main drawback seems that it has less functionalities. For instance I was using a search filter on some tables (with `name@_ilike`) and it's not supported by the other package (see https://github.com/hasura/ra-data-hasura/issues/13).

For the record, I also found a horrible hack for my initial issue... I'm catching the error when building the hasura provider and set a "fake" data provider as a fallback (just to get react-admin to boot and redirect to the login page). Whenever the user logs in, I try to build the hasura provider again.

``` js
const dummyDataProvider = fakeDataProvider({
  User: [],
})

const App = () => {
  const [dataProvider, setDataProvider] = React.useState();

  var tryToBuildHasuraProvider = function() { 
    buildHasuraProvider({
      client: client,
    })
    .then((dp) => setDataProvider(() => dp))
    .catch(e => {
      setDataProvider(() => dummyDataProvider)
    });
  };

  React.useEffect(() => {
    firebaseApp.auth().onAuthStateChanged(function(user) {
        tryToBuildHasuraProvider();
    });
    tryToBuildHasuraProvider();
  }, []);

  if (!dataProvider) {
    return <div>Loading</div>;
  }

  return (
    <Admin authProvider={authProvider} dataProvider={dataProvider}>
      <Resource name="User" icon={UserIcon} list={UserList} create={UserCreate} edit={UserEdit} />
    </Admin>
  );
};
```

**Comment by johnparn** [comment]
Hi @bamarni and @dvasdekis!

I know this issue is closed, but I got a question how you got this to work. There is something fishy around this that I can't wrap my head around. 

I've tried to supply both supplying `clientOptions` and `client` to the `buildHasuraProvider`, but neither works. With the latter, client, I had to setup a dummy provider, like you did @bamarni, in order to be able to direct the user to the login page.

If the user signs in the token is set and applied to the requests. But the introspections query does not work properly. @dvasdekis, I think you mentioned something about that in another issue and you ended up creating a new httpClient to get around that.

Haven't you been bitten by this? This is my messy code.


```
import React, { useEffect, useState } from 'react';
import { Admin, fetchUtils, Resource } from 'react-admin';
import buildHasuraProvider from 'ra-data-hasura-graphql';
import Titles from './resources/titles';
import Languages from './resources/languages';

import Publishers from './resources/publishers';
import Contributors from './resources/contributors';

import Auth, { firebaseApp } from './firebase-auth';
import {
  ApolloClient,
  createHttpLink,
  from,
  InMemoryCache,
} from '@apollo/client';
import { setContext } from '@apollo/client/link/context';
import { onError } from '@apollo/client/link/error';
import { path as rpath } from 'ramda';
import fakeDataProvider from 'ra-data-fakerest';

const App = () => {
  const [dataProvider, setDataProvider] = useState();

  const dummyDataProvider = fakeDataProvider({
    User: [],
  });

  const httpLink = createHttpLink({
    uri: process.env.REACT_APP_HASURA_URI,
  });

  const authLink = setContext((_, { headers }) => {
    const token = localStorage.getItem('token') || null;

    return token
      ? {
          headers: {
            ...headers,
            Authorization: `Bearer ${token}`,
          },
        }
      : {
          headers: {
            ...headers,
          },
        };
  });

  const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors)
      graphQLErrors.map((error) => {
        const { locations, path } = error.extensions;
        const message = rpath(['message'], error);

        const code = rpath(['extensions', 'code'], error);

        if (code === 'invalid-jwt') {
          console.log(code);
          Auth.logout();
        } else if (code === 'invalid-headers') {
          console.log(code);
          Auth.logout();
        }
        console.log(`[GraphQL error]: Code: ${JSON.stringify(error)}`);
      });
    if (networkError) console.log(`[Network error]: ${networkError}`);
  });

  const client = new ApolloClient({
    link: from([errorLink, authLink, httpLink]),
    cache: new InMemoryCache(),
  });

  const buildDataProvider = async () => {
    return buildHasuraProvider({
      client,
    })
      .then((dp) => setDataProvider(() => dp))
      .catch((e) => {
        setDataProvider(() => dummyDataProvider);
      });
  };

  useEffect(() => {
    // Create DataProvider
    const provider = async () => {
      await buildDataProvider();
    };

    // Setup listener for auth state
    firebaseApp.auth().onAuthStateChanged(async (user) => {
      if (user) {
        user
          .getIdToken()
          .then(async (token) => {
            localStorage.setItem('token', token);
            await buildDataProvider();
          })
          .catch((e) => {
            Auth.logout();
          });
      }
    });

    provider();
  }, []);

  if (!dataProvider) {
    return <div>Loading</div>;
  }

  return (
    <Admin dataProvider={dataProvider} authProvider={Auth}>
      <Resource
        options={{ label: 'Titles' }}
        name="metadata_titles"
        {...Titles}
      />
    </Admin>
  );
};

export default App;


```

**Comment by johnparn** [comment]
@bamarni and @dvasdekis ! got it working. I had to unset dataProvider by doing `setDataProvider()` before assigning a new data provider. Now it works.

To spare the hair of any other who struggles with this, this is the code I have working (not cleaned up yet):


```
import React, { useEffect, useState } from 'react';
import { Admin, fetchUtils, Resource } from 'react-admin';
import buildHasuraProvider from 'ra-data-hasura-graphql';
import Titles from './resources/titles';

import Auth, { firebaseApp } from './firebase-auth';
import {
  ApolloClient,
  createHttpLink,
  from,
  InMemoryCache,
} from '@apollo/client';
import { setContext } from '@apollo/client/link/context';
import { onError } from '@apollo/client/link/error';
import { path as rpath } from 'ramda';
import fakeDataProvider from 'ra-data-fakerest';

const App = () => {
  const [dataProvider, setDataProvider] = useState();

  const dummyDataProvider = fakeDataProvider({
    User: [],
  });

  const httpLink = createHttpLink({
    uri: process.env.REACT_APP_HASURA_URI,
  });

  const authLink = setContext((_, { headers }) => {
    const token = localStorage.getItem('token') || null;

    return token
      ? {
          headers: {
            ...headers,
            Authorization: `Bearer ${token}`,
          },
        }
      : {
          headers: {
            ...headers,
          },
        };
  });

  const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors)
      graphQLErrors.map((error) => {
        const { locations, path } = error.extensions;
        const message = rpath(['message'], error);

        const code = rpath(['extensions', 'code'], error);

        if (code === 'invalid-jwt') {
          console.log(code);
          Auth.logout();
        } else if (code === 'invalid-headers') {
          console.log(code);
          Auth.logout();
        }
        console.log(`[GraphQL error]: Code: ${JSON.stringify(error)}`);
      });
    if (networkError) console.log(`[Network error]: ${networkError}`);
  });

  const client = new ApolloClient({
    link: from([errorLink, authLink, httpLink]),
    cache: new InMemoryCache(),
  });

  const buildDataProvider = async () => {
    return buildHasuraProvider({
      client,
    })
      .then((dp) => setDataProvider(() => dp))
      .catch((e) => {
        setDataProvider(() => dummyDataProvider);
      });
  };

  useEffect(() => {
    // Create DataProvider
    const provider = async () => {
      try {
        await buildDataProvider();
      } catch (e) {}
    };

    // Setup listener for auth state
    firebaseApp.auth().onAuthStateChanged(async (user) => {
      if (user) {
        user
          .getIdToken()
          .then(async (token) => {
            // Unset data provider - just doing an assignment over the dummy provider does not work
            setDataProvider();
            localStorage.setItem('token', token);
            await buildDataProvider();
          })
          .catch(async (e) => {
            // Not token means user isn't signed in, but RA requires a data provider
            await buildDataProvider();
            Auth.logout();
          });
      }
    });

    provider();
  }, []);

  if (!dataProvider) {
    return <div>Loading</div>;
  }

  return (
    <Admin dataProvider={dataProvider} authProvider={Auth}>
      <Resource
        options={{ label: 'Titles' }}
        name="metadata_titles"
        {...Titles}
      />
    </Admin>
  );
};

export default App;

```
