### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by ryanberckmans** [Steams/ra-data-hasura-graphql#28]
Please add a LICENSE :)  ... MIT?

Thank you so much for making this.

**Comment by wald-tq** [comment]
It is already in package.json, maybe just add MIT license with a PR?

**Comment by ryanberckmans** [comment]
@wald-tq done.

@Steams https://github.com/Steams/ra-data-hasura-graphql/pull/31

**Comment by Steams** [comment]
Thanks guys
