### ISSUE TITLE
Question: access to aggregations through list view

### ISSUE THREAD

**Issue by austinrivas** [Steams/ra-data-hasura-graphql#37]
Since hasura publishes aggregations for each resource it should be possible to translate this query:

```graphql
query MyQuery {
  companies {
    name
    users_aggregate {
      aggregate {
        count
      }
    }
  }
}
```

into a table resembling

```jsx
<List {...props}>
    <Datagrid>
      <TextField source="name" />
      <TextField source="users_aggregate.aggregate.count" />
    </Datagrid>
</List>
```

Is this currently possible or within the scope of this dataprovider?

**Comment by cpv123** [comment]
Yes, this is possible. 

Following the steps here https://github.com/Steams/ra-data-hasura-graphql#customize-fields-variables-responseparser you could create a `buildFieldsCustom` function like so
```
const buildFieldsCustom = type => {
  let res = buildFields(type);
  if (type.name === 'companies') {
    // here we add additional fields we want to query for companies resource.
    res.push(
      gqlTypes.field(
        gqlTypes.name('users_aggregate'),
        null,
        null,
        null,
        gqlTypes.selectionSet([
          gqlTypes.field(
            gqlTypes.name('aggregate'),
            null,
            null,
            null,
            gqlTypes.selectionSet([gqlTypes.field(gqlTypes.name('count'))]),
          ),
        ]),
      ),
    );
  }
  return res;
};
```
which would then allow access to `users_aggregate.aggregate.count` in the List view.

Might be worth writing a generic `addAggregateCount` to hide some of that GraphQL AST!

**Comment by austinrivas** [comment]
Thanks @cpv123 

You looking for a job by any chance?

**Comment by cpursley** [comment]
This is an interesting idea @austinrivas - feel free to reopen
