### ISSUE TITLE
pagination issue

### ISSUE THREAD

**Issue by jamesfx2000** [Steams/ra-data-hasura-graphql#4]
When using the `<List>` component pagination doesn't work.

I had a look at this demo which also has the issue: 
https://github.com/cpursley/react-admin-low-code

I think the problem arises because the limit is being applied to the aggregate query.

`person_aggregate(limit: $limit, offset: $offset, order_by: $order_by, where: $where)`

Thanks for creating this.

**Comment by Steams** [comment]
Thanks for letting me know, I still have a bit of work and cleanup to do on the library that i wasn't able to tackle over the holiday, it isn't yet ready for use but should be soon.
