### ISSUE TITLE
Doc improvement: Passing headers in the GraphQL requests

### ISSUE THREAD

**Issue by csadai** [Steams/ra-data-hasura-graphql#45]
Hi,

I've read the `README` which invites me to create a dedicated `Apollo Boost` instantiation in order to pass some `headers` to my requests. 

It's actually possible to pass those using the default connection, by supplying a GraphQL-Link object in lieu of the `uri` parameter.

e.g.

```javascript
import { HttpLink } from 'apollo-link-http'
(....)
 componentDidMount() {
    buildHasuraProvider({
      clientOptions: {
        link: new HttpLink({
          uri: "http://localhost:8080/v1/graphql",
          headers: {
            "x-hasura-admin-secret": "my-password",
          }
        })
      }
    })
    .then(dataProvider => this.setState({ dataProvider }));
}
```

You may want to update the documentation with it, as it's probably easier than redoing the whole connection (handling cache, etc.)

**Comment by webdeb** [comment]
Its already there:
https://github.com/Steams/ra-data-hasura-graphql#customize-the-apollo-client

**Comment by webdeb** [comment]
Probably making the word "otherApolloOptions" to be a link to https://www.apollographql.com/docs/react/api/apollo-client/#ApolloClientOptions is a good idea.

**Comment by csadai** [comment]
Yes, but as stated in my ticket, the recommendation to bring your own client is overkill, when you can benefit from all the underlying client of `ra-data-graphql` by just providing a `httpLink`.
This is not a bug nor a problem, just a recommendation for those finding this ticket while searching for something simpler.

**Comment by csadai** [comment]
> Probably making the word "otherApolloOptions" to be a link to https://www.apollographql.com/docs/react/api/apollo-client/#ApolloClientOptions is a good idea.

Absolutely
