### ISSUE TITLE
Convert search to ilike

### ISSUE THREAD

**Issue by cpursley** [Steams/ra-data-hasura-graphql#5]
Search is simply doing an `_eq` comparison which means it will be an exact match:

`{where: {_and: [{name: {_eq: "search term"}}]}, limit: 10, offset: 0, order_by: {id: "asc"}}`

Can you change this so that it's more flexible where it can match multiple combinations (partial name, case insensitive)?

Maybe something like this:

`{where: {_and: [{name: {_ilike: "search term"}}]}, limit: 10, offset: 0, order_by: {id: "asc"}}`

**Comment by Steams** [comment]
Closed by 5470bec44f0bd4978ca134415541014b5b7aa587
