### ISSUE TITLE
404 error -resource does not exist - code not found

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [Steams/ra-data-hasura-graphql#51]
Hello,

I am using ra-data-hasura-graphsql in my react-admin project. The repo is at:
https://github.com/affluent-bilby-classifieds/express-hasura_ra-cb-menu

I haven't setup the admin-secret or the authentication in apollo-boost yet in case that is my issue. It's running on a VM on my LAN behind NAT. I am using the authentication that came with the initial project I forked mine from which uses express-jwt.  

I can access the hasura console OK.

However in react-admin I just get the message: Loading...

My issue looks like this (please scroll to the right to see the debug console):

[Screenshot](https://github.com/affluent-bilby-classifieds/express-hasura_ra-cb-menu/blob/master/Screenshot%20from%202020-07-08%2015-36-46.png)

I have tried changing App.js: clientOptions: { uri: 'http://localhost:8080' }, 
to the IP of the VM. That is the configuration used in the screenshot. 

I have also allowed insecure content in Chrome for that IP and port. Any help finding the cause of this issue so I can get this up and running would be much appreciated. I apologize if I have missed anything but I have tried many different data providers to finally up here with ra-data-hasura-graphql so hopefully I will soon have it working. Let me know if there are any other steps you want me to try. Thank you.

headers:

```
Request URL: http://192.168.1.131:8080/
Request Method: POST
Status Code: 404 Not Found
Remote Address: 192.168.1.131:8080
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
Access-Control-Allow-Origin: http://192.168.1.131:3000
Content-Type: application/json; charset=utf-8
Date: Wed, 08 Jul 2020 07:14:40 GMT
Server: Warp/3.2.27
Transfer-Encoding: chunked
accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 1922
content-type: application/json
Host: 192.168.1.131:8080
Origin: http://192.168.1.131:3000
Referer: http://192.168.1.131:3000/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/83.0.4103.116 Chrome/83.0.4103.116 Safari/537.36
{operationName: "IntrospectionQuery", variables: {},…}
operationName: "IntrospectionQuery"
query: "query IntrospectionQuery {↵  __schema {↵    queryType {↵      name↵      __typename↵    }↵    mutationType {↵      name↵      __typename↵    }↵    subscriptionType {↵      name↵      __typename↵    }↵    types {↵      ...FullType↵      __typename↵    }↵    directives {↵      name↵      description↵      locations↵      args {↵        ...InputValue↵        __typename↵      }↵      __typename↵    }↵    __typename↵  }↵}↵↵fragment FullType on __Type {↵  kind↵  name↵  description↵  fields(includeDeprecated: true) {↵    name↵    description↵    args {↵      ...InputValue↵      __typename↵    }↵    type {↵      ...TypeRef↵      __typename↵    }↵    isDeprecated↵    deprecationReason↵    __typename↵  }↵  inputFields {↵    ...InputValue↵    __typename↵  }↵  interfaces {↵    ...TypeRef↵    __typename↵  }↵  enumValues(includeDeprecated: true) {↵    name↵    description↵    isDeprecated↵    deprecationReason↵    __typename↵  }↵  possibleTypes {↵    ...TypeRef↵    __typename↵  }↵  __typename↵}↵↵fragment InputValue on __InputValue {↵  name↵  description↵  type {↵    ...TypeRef↵    __typename↵  }↵  defaultValue↵  __typename↵}↵↵fragment TypeRef on __Type {↵  kind↵  name↵  ofType {↵    kind↵    name↵    ofType {↵      kind↵      name↵      ofType {↵        kind↵        name↵        ofType {↵          kind↵          name↵          ofType {↵            kind↵            name↵            ofType {↵              kind↵              name↵              ofType {↵                kind↵                name↵                __typename↵              }↵              __typename↵            }↵            __typename↵          }↵          __typename↵        }↵        __typename↵      }↵      __typename↵    }↵    __typename↵  }↵  __typename↵}↵"
variables: {}
```
preview:
```
{path: "$", error: "resource does not exist", code: "not-found"}
code: "not-found"
error: "resource does not exist"
path: "$"
```
response:
```
{"path":"$","error":"resource does not exist","code":"not-found"}
```

**Comment by webdeb** [comment]
```
{"path":"$","error":"resource does not exist","code":"not-found"}
```
could mean, that your current user is not authorised to do anything on the resource.

**Comment by affluent-bilby-classifieds** [comment]
webdeb that's a good point. 
I could enable verbose logging for pg.
Should I add: command: ["postgres", "-c", "log_statement=all"] to my docker-compose file?

**Comment by webdeb** [comment]
I guess you only have to set the right auth headers in your `react-admin` 

Something like this:

```
  componentDidMount() {
    const httpLink = createHttpLink({ uri: process.env.REACT_APP_GRAPHQL_URI });
    const middlewareLink = new ApolloLink((operation, forward) => {
      operation.setContext({
        headers: {
          Authorization: "Bearer " + yourToken, // <--- SET THE TOKEN
        },
      });
      return forward(operation);
    });

    // use with apollo-client
    const link = middlewareLink.concat(httpLink);

    buildHasuraProvider({
      clientOptions: { link: link },
    }).then((dataProvider) =>
      this.setState({
        dataProvider: enhanceDataProvider(dataProvider),
      })
    );
```

**Comment by affluent-bilby-classifieds** [comment]
This gives me a lead to follow. Thanks webdeb. Is this similar to the section "Authentication" (where it says 
To send authentication headers, declare your own apollo client.) on the readme.md file?

**Comment by webdeb** [comment]
> Is this similar to the section "Authentication" (where it says
To send authentication headers, declare your own apollo client.) on the readme.md file?

its exactly this

**Comment by dknight10** [comment]
Maybe you're missing the complete URL? I got this error when trying the base `http://localhost:8080` but noticed that my Hasura endpoint was actually `http://localhost:8080/v1/graphql`

**Comment by affluent-bilby-classifieds** [comment]
Hi dknight10,

Thanks for the suggestion. I tried that.
It seems to get further but still fails. I should probably continue with webdebs suggestion.
![Screenshot from 2020-07-09 13-31-36](https://user-images.githubusercontent.com/40859915/87000992-f5490c00-c1e8-11ea-876a-8b0a0687af7d.png)j

![Screenshot from 2020-07-09 13-31-34](https://user-images.githubusercontent.com/40859915/87000981-eeba9480-c1e8-11ea-8420-d61c803fe145.png)

**Comment by affluent-bilby-classifieds** [comment]
I tried the nginx configuration above.

I am back to the "Loading" message so no react-admin screen.
In the console I get:
``` 
index.js:16713 Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at index.js:16713
    at Array.reduce (<anonymous>)
    at index.js:16712
    at index.js:16526
    at Object.next (index.js:16539)
    at a (index.js:16427)
```

**Comment by affluent-bilby-classifieds** [comment]
Is there another example implementation I can learn from?

The [App.tsx](https://github.com/cpursley/react-admin-low-code/blob/master/src/App.tsx) file in [react-admin-low-code](https://github.com/cpursley/react-admin-low-code/) looks nothing like the [App.js](https://github.com/affluent-bilby-classifieds/express-hasura_ra-cb-menu/blob/master/front/src/App.js) in my [project](https://github.com/affluent-bilby-classifieds/express-hasura_ra-cb-menu)

I can see the is defined in [get-app.tsx](https://github.com/cpursley/react-admin-low-code/blob/master/src/get-app.tsx) but I use js.

**Comment by webdeb** [comment]
@affluent-bilby-classifieds 
To start simple, I would try to run a basic hasura installation, maybe just spin up an official heroku deployment for free.

---
"Bearer" is part of the OAuth2.0 Authorization Scheme. Just search for it, if you need more information. "Bearer JWT" should give you enough posts about this.

**Comment by affluent-bilby-classifieds** [comment]
Thank you webdeb. Those are great ideas. You have given me enough information for me to continue working so I will close this ticket now. I feel more confident this morning so I wish to thank you sincerely.
