### ISSUE TITLE
Help requested: authentication code block

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [Steams/ra-data-hasura-graphql#54]
Hello,

I am trying to get up and running with a test RA/Hasura dashboard. I have used a mix of the code in the readme.md and a code snippet example given by webdeb [here](https://github.com/Steams/ra-data-hasura-graphql/issues/51#issuecomment-655376912).

For now instead of bearer I have just enabled the secret key. I don't mind changing this and expect I will need to at some point based on the authentication and security model used by Hasura.

For context here is my full github [repo](https://github.com/affluent-bilby-classifieds/express-hasura_ra-cb-menu).
Here is the code snippet from the [App.js](https://github.com/affluent-bilby-classifieds/express-hasura_ra-cb-menu/blob/master/front/src/App.js) in my repo. 

Any assistance would be much appreciated and I will pay it forward by helping write documentation for beginners.

I have changed the code-block to:
```
/* testing this code  */

componentDidMount() { 
  const httpLink = createHttpLink({ uri: 'http://hasura:8080/v1/graphql' });
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: {
      'x-hasura-admin-secret': `myadminsecretkey`,
        /* Authorization: "Bearer " + yourToken, // <--- SET THE TOKEN */
      },
    });
    return forward(operation);
  });

  // use with apollo-client
  const link = middlewareLink.concat(httpLink);

  buildHasuraProvider({
    clientOptions: { link: link },
  }).then((dataProvider) =>
    this.setState({
      dataProvider: enhanceDataProvider(dataProvider),
    })
  );
/* end test  */
```

Please note I haven't tried building it yet because the first '{' after componentDidMount() has red underline squiggle and gives the message: ';' expected. ts(1005)   
This is in visual studio code. 

If we look at the instructions and example code in the readme.md for "ra-data-hasura-graphql" we have:

## Authentication

To send authentication headers, declare your own apollo client.
```
import ApolloClient from 'apollo-boost';

const client = new ApolloClient({
  uri: 'http://localhost:8080/v1/graphql',
  headers: {
    'x-hasura-admin-secret': `myadminsecretkey`,
    // 'Authorization': `Bearer xxxx`,
  }
});

// When building your provider inside your component
// set up the client like this
buildHasuraProvider({ client })
```

So I don't know what is meant to be in 'client' so I have referred to the code snippet provided by webdeb. However, that code snippet hasn't actually called ApolloClient and I can tell as the "import" line is still still faded in visual studio code.   

[gmatht](https://github.com/gmatht) is helping with the project too. 
@gmatht perhaps these will help us? 
[Set up a GraphQL client with Apollo](https://hasura.io/learn/graphql/react/apollo-client/)
[React componentDidMount](https://reactjs.org/docs/react-component.html#componentdidmount)

**Comment by affluent-bilby-classifieds** [comment]
OK looks like I missed const link = middlewareLink.concat(httpLink);

**Comment by affluent-bilby-classifieds** [comment]
I have changed the code-block to:
```
/* testing this code  */

componentDidMount() { 
  const httpLink = createHttpLink({ uri: 'http://hasura:8080/v1/graphql' });
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: {
      'x-hasura-admin-secret': `myadminsecretkey`,
        /* Authorization: "Bearer " + yourToken, // <--- SET THE TOKEN */
      },
    });
    return forward(operation);
  });

  // use with apollo-client
  const link = middlewareLink.concat(httpLink);

  buildHasuraProvider({
    clientOptions: { link: link },
  }).then((dataProvider) =>
    this.setState({
      dataProvider: enhanceDataProvider(dataProvider),
    })
  );
/* end test  */
```

Please note I haven't tried building it yet because the first '{' over componentDidMount() has red underline squiggle and gives the message: ';' expected. ts(1005)

**Comment by affluent-bilby-classifieds** [comment]
OK I know this code still doesn't work but am I at least on the right track?
I noticed I had buildHasuraProvider twice so I commented out the first one.

I have copied the imports from the "Set up a GraphQL client with Apollo" part of the tutorial but most of them aren't used yet as they are still faded.
```
// in App.js
import React, { Component } from 'react';
import buildHasuraProvider from 'ra-data-hasura-graphql';
import { Admin, Resource } from 'react-admin';
import { ItemList, ItemEdit, ItemCreate } from './items';
import ApolloClient from 'apollo-boost';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';
import { ApolloProvider } from '@apollo/react-hooks';


class App extends Component {
    constructor() {
        super();
        this.state = { dataProvider: null };
    }
    /* componentDidMount() {
        buildHasuraProvider({
            clientOptions: { uri: 'http://hasura:8080/v1/graphql' },
        }).then((dataProvider) => this.setState({ dataProvider }));
    } */

    
/* testing this code  */

componentDidMount() {
  const httpLink = createHttpLink({ uri: 'http://hasura:8080/v1/graphql' });
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: {
      'x-hasura-admin-secret': `myadminsecretkey`,
        /* Authorization: "Bearer " + yourToken, // <--- SET THE TOKEN */
      },
    });
    return forward(operation);
  });

  // use with apollo-client
  const link = middlewareLink.concat(httpLink);

  buildHasuraProvider({
    clientOptions: { link: link },
  }).then((dataProvider) =>
    this.setState({
      dataProvider: enhanceDataProvider(dataProvider),
    })
  );
/* end test  */


render() {
  const { dataProvider } = this.state;

  if (!dataProvider) {
      return <div>Loading</div>;
  }

  return (
      <Admin dataProvider={dataProvider}>
          <Resource name="items" list={ItemList} edit={ItemEdit} create={ItemCreate} />
      </Admin>
  );
}
}


export default App;

```

**Comment by affluent-bilby-classifieds** [comment]
@gmatht advised me: "I think that parse error is because "componentDidMount() {" is not inside the class."

I tried TSLint but that doesn't do much more than my vs code does anyway.

**Comment by webdeb** [comment]
you are missing a curly bracket after the componentDidMount block, also you are using my example with `enhanceDataProvider` which is not defined in your code. so just remove it.

**Comment by affluent-bilby-classifieds** [comment]
Like this?
``
// in App.js
import React, { Component } from 'react';
import buildHasuraProvider from 'ra-data-hasura-graphql';
import { Admin, Resource } from 'react-admin';
import { ItemList, ItemEdit, ItemCreate } from './items';
import ApolloClient from 'apollo-boost';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink, createHttpLink, ApolloLink } from 'apollo-link-http';
import { ApolloProvider } from '@apollo/react-hooks';


class App extends Component {
    constructor() {
        super();
        this.state = { dataProvider: null };
    }
    /* componentDidMount() {
        buildHasuraProvider({
            clientOptions: { uri: 'http://hasura:8080/v1/graphql' },
        }).then((dataProvider) => this.setState({ dataProvider }));
    } */

    
/* testing this code  */

componentDidMount() {
  const httpLink = createHttpLink({ uri: 'http://hasura:8080/v1/graphql' });
  const middlewareLink = new ApolloLink((operation, forward) => {
    operation.setContext({
      headers: {
      'x-hasura-admin-secret': `myadminsecretkey`,
        /* Authorization: "Bearer " + yourToken, // <--- SET THE TOKEN */
      }
      },
    });
    return forward(operation);
  });

  // use with apollo-client
  const link = middlewareLink.concat(httpLink);

  buildHasuraProvider({
    clientOptions: { link: link },
 
    })
  );
/* end test  */


render() {
  const { dataProvider } = this.state;

  if (!dataProvider) {
      return <div>Loading</div>;
  }

  return (
      <Admin dataProvider={dataProvider}>
          <Resource name="items" list={ItemList} edit={ItemEdit} create={ItemCreate} />
      </Admin>
  );
}
}


export default App;
```

**Comment by webdeb** [comment]
I don't think that the issue board is for this kind of questions. There are platforms where people help others to fix their code and explain basics.

**Comment by affluent-bilby-classifieds** [comment]
sure, can I please ask what is the simplest possible App.js file that will work with ra-data-hasura-graphql?

**Comment by affluent-bilby-classifieds** [comment]
I do see the following in the readme.md:

## Options

### Customize the Apollo client

You can either supply the client options by calling `buildGraphQLProvider` like this:

```js
buildGraphQLProvider({
    clientOptions: { uri: 'http://localhost:4000', ...otherApolloOptions },
});
```

Or supply your client directly with:

```js
buildGraphQLProvider({ client: myClient });
```
It might be easier for me to try the otherApolloOptions option on the first example.

**Comment by cpursley** [comment]
Take a look at these following repos:

- https://github.com/cpursley/react-admin-low-code
- https://github.com/dvasdekis/react-admin-hasura-firebase
- https://github.com/hgiasac/ra-hasura-typescript-boilerplate

Or any of these "Used By" repos:

https://github.com/Steams/ra-data-hasura-graphql/network/dependents?package_id=UGFja2FnZS03NzE0NzgxNjA%3D

**Comment by affluent-bilby-classifieds** [comment]
Thanks cpursely. I have been looking at the [auth file](https://github.com/hgiasac/hasura-typescript-boilerplate/blob/auth-jwt/services/auth/src/handler/auth.ts) from ra-hasura-typescript-boilerplate.

And it is interesting how it details the following in the readme.me: 
    services/auth: Authentication webhook
    services/data: Hasura GraphQL project with migrations
    services/events: Event triggers
    services/actions: Hasura actions

and how it uses Next.js + Tailwind for the back-end as my project uses Express.js and I was considering using Bulma at some in the future. The thought had crossed my mind to spin it up on a VM and see if I can just work with it.

I am also particularly interested in the [docker-compose file](https://github.com/dvasdekis/react-admin-hasura-firebase/blob/master/docker-compose.yaml) from react-admin-hasura-firebase.

I wasn't sure where to find the auth code in react-admin-low-code[https://github.com/cpursley/react-admin-low-code/](https://github.com/cpursley/react-admin-low-code/) which is ironically in your repo.

That "Used By" will link come in handy and I was looking for that.

**Comment by affluent-bilby-classifieds** [comment]
Would something like this work? 

```
componentDidMount() {
    buildHasuraProvider({ clientOptions: {
       uri: 'http://hasura:8080/v1/graphql',
       headers: {'x-hasura-admin-secret': `myadminsecretkey`},  
      } })
      .then(dataProvider => this.setState({ dataProvider }));
  }


```

**Comment by webdeb** [comment]
Just do it like its shown in the readme
https://github.com/Steams/ra-data-hasura-graphql#authentication

**Comment by affluent-bilby-classifieds** [comment]
> Just do it like its shown in the readme
> https://github.com/Steams/ra-data-hasura-graphql#authentication

Yes, I didn't quite understand the readme at first but I am going to try the code tomorrow to see if it works.
Thanks webdeb.
