### ISSUE TITLE
Error: Unknown resource undefined. Make sure it has been declared on your server side schema

### ISSUE THREAD

**Issue by nythrox** [Steams/ra-data-hasura-graphql#6]
Hi, when I run the following code
```

import buildHasuraProvider from "ra-data-hasura-graphql";

  const [dataProvider, setDataProvider] = useState(null);

  useEffect(() => {
    console.log(dataProvider);
    if (!dataProvider)
      buildHasuraProvider({
        clientOptions: {
          uri: "https://good-start.herokuapp.com/v1/graphql",
        }
      }).then(dataProvider => {
        setDataProvider(dataProvider);
      });
  });

  if (!dataProvider) {
    return <div>Loading</div>;
  } else
    return (
      <Admin dataProvider={dataProvider}>
         <Resource
           name="users"
           list={ListGuesser}
           show={ShowGuesser}
           edit={EditGuesser}
         />
      </Admin>
    );
```

The future never completes and ends up throwing the error
```
Uncaught Error: Unknown resource undefined. Make sure it has been declared on your server side schema. Known resources are 
    at index.js:16
    at T (index.js:16)
    at index.js:16
    at basicStateReducer (react-dom.development.js:16445)
    at updateReducer (react-dom.development.js:16591)
    at updateState (react-dom.development.js:16640)
    at Object.useState (react-dom.development.js:17363)
    at useState (react.development.js:1619)
    at App (App.js:42)
    at renderWithHooks (react-dom.development.js:16260)
    at updateFunctionComponent (react-dom.development.js:18347)
    at beginWork$1 (react-dom.development.js:20176)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25780)
    at performUnitOfWork (react-dom.development.js:24695)
    at workLoopSync (react-dom.development.js:24671)
    at performSyncWorkOnRoot (react-dom.development.js:24270)
    at react-dom.development.js:12199
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12194)
    at flushSyncCallbackQueue (react-dom.development.js:12182)
    at scheduleUpdateOnFiber (react-dom.development.js:23709)
    at dispatchAction (react-dom.development.js:17076)
    at App.js:75
```
Do you have any idea of what could be causing this? I believe it's not a react-admin issue since the Admin component never even has a chance to render, given that the error is thrown before.

![image](https://user-images.githubusercontent.com/41273690/71741384-8a83d600-2e3d-11ea-8055-a514fa249aeb.png)

The actual request seems to be correct and scucesfully completes with no errors. (200 code)

P.S: My hasura server has a admin secret, could it be that?

**Comment by cpursley** [comment]
This looks like the easiest way to add custom headers (admin secret) until this library has a full authprovider implementation:

https://marmelab.com/react-admin/DataProviders.html#adding-custom-headers

**Comment by nythrox** [comment]
Hi, thanks for the answer.
The client is now accessing hasura with the admin secret, but it's still giving this error:
![image](https://user-images.githubusercontent.com/41273690/71772689-03625b00-2f2e-11ea-90a7-2b7af11c66dc.png)

**Comment by Steams** [comment]
What is the name of the resource you are creating components for ? The introspection seems to be picking up the schema of your Hasura endpoint properly so it seems like an issue with an incorrectly worded resource. 
Can you share a screenshot of the code that declares the react admin resources ?

**Comment by nythrox** [comment]
Hi @Steams, currently it has an empty Admin declaration, but it throws the same error when all the resources are declared.
I think the problem is not the resources since they worked the ra-data-hasura provider and the error says "undefined" isn't declared.
Could it be something in my Hasura is not supported? I'm using v1.0.0-beta.6
![image](https://user-images.githubusercontent.com/41273690/71791824-1c920700-3015-11ea-8d57-0def1d6e8db7.png)
Code with declared resources (same error):
`
      <Admin dataProvider={dataProvider}>
        <Resource
        name="levels"
        list={LevelList}
        edit={LevelEdit}
        create={LevelCreate}
        show={LevelShow}
      />
      <Resource
        name="exercises"
        list={ExerciseList}
        edit={ExerciseEdit}
        create={ExerciseCreate}
        show={ExerciseShow}
      />
      <Resource
        name="questions"
        list={QuestionList}
        show={QuestionShow}
        create={QuestionCreate}
        edit={QuestionEdit}
      />
      <Resource
        name="answers"
        list={AnswerList}
        show={AnswerShow}
        edit={AnswerEdit}
        create={AnswerCreate}
      />
      <Resource
        options={{ label: "Explanations" }}
        name="answer_explanations"
        list={ExplanationList}
        show={ExplanationShow}
        edit={ExplanationEdit}
        create={ExplanationCreate}
      />
      <Resource
        options={{ label: "Question Types" }}
        name="question_types"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      />
      <Resource
        options={{ label: "Images" }}
        name="question_images"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      />
      <Resource
        name="videos"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      />
      <Resource
        name="users"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      />
      <Resource
        name="clients"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      />
      <Resource
        name="students"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      />
      <Resource
        name="exercise_layout_types"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      />
      <Resource
        name="student_answers"
        list={ListGuesser}
        show={ShowGuesser}
        edit={EditGuesser}
      /> 
      </Admin>
`

**Comment by Steams** [comment]
@nythrox , from all appearances, the problem you're having seems to be on the react admin side. Was this application was working before using a different adapter ? 

That error is only thrown by the first part of the data provider that gets called by react admin, and it is reporting that it was called with an undefined value for "resourceName", which is a value received directly from react admin when it calls into my code. 

![Screenshot_20200106_080911](https://user-images.githubusercontent.com/6764429/71820112-28ed8280-305c-11ea-9bb8-d94059fcf048.png)

**Comment by nythrox** [comment]
@Steams It was working with the other Hasura data provider, but RA was giving problems of its own, for some reason it had plenty of bugs and a lot of widgets didn't work. Thank you for your help, I'm closing the issue.

**Comment by mutewinter** [comment]
I ran into the same series of errors here and I found a solution: the component that awaits the promise of `buildHasuraProvider` needs to be a class component, like in the README for this project.

# Works

```tsx
class AppWrapper extends React.Component<{}, { resolvedDataProvider: any }> {
  constructor(props: any) {
    super(props);
    this.state = { resolvedDataProvider: null };
  }

  async componentDidMount() {
    this.setState({
      resolvedDataProvider: await buildHasuraProvider({
        clientOptions: { uri: "http://localhost:1234/v1/graphql" }
      })
    });
  }

  render() {
    const { resolvedDataProvider } = this.state;

    if (!resolvedDataProvider) {
      return <div>Loading...</div>;
    }

    return <App dp={resolvedDataProvider} />;
  }
}
```

# Causes the `Error: Unknown resource undefined` error

```tsx
const AppWrapper = () => {
  const [resolvedDataProvider, setResolvedDataProvider] = React.useState();

  React.useEffect(() => {
    (async () => {
      setResolvedDataProvider(
        await buildHasuraProvider({
          clientOptions: { uri: "http://localhost:1234/v1/graphql" }
        })
      );
    })();
  }, []);

  if (!resolvedDataProvider) {
    return <div>Loading...</div>;
  }

  return <App dp={resolvedDataProvider} />;
};
```

**Comment by mutewinter** [comment]
Here's why, and the fix: https://github.com/marmelab/react-admin/issues/3340. Working code with hooks:

```tsx
  const [resolvedDataProvider, setResolvedDataProvider] = React.useState();

  React.useEffect(() => {
    (async () => {
      const dp = await dataProvider;
      setResolvedDataProvider(() => dp);
    })()
  }, []);

  if (!resolvedDataProvider) {
    return <div>Loading...</div>;
  }
```
