### ISSUE TITLE
Filters broken in latest release (ilike)

### ISSUE THREAD

**Issue by cpursley** [Steams/ra-data-hasura-graphql#7]
**ilike** is only going to work for text search. The latest changes break all other filter types:

`GraphQL error: field "_ilike" not found in type: 'Boolean_comparison_exp'`

`GraphQL error: field "_ilike" not found in type: 'timestamptz_comparison_exp'`

Perhaps there is a way to switch to `_ilike` for search fields and `_eq` for the others?

**Comment by Steams** [comment]
Fixed by 8e0e829add3c7cfcb56e28b3c77870ae1b46c74d
